### ISSUE TITLE
Add ability to run init containers separately

### ISSUE THREAD

**Issue by timothyb89** [monasca/monasca-helm#20]
It would be nice if there was some ability to run only some init containers in case things need to be restarted, for instance during an upgrade. Right now if `helm upgrade` deletes anything and persistent storage isn't enabled, the Monasca deployment will be left in a bad state.

Alternatively, making Helm smart enough to re-run init containers when it upgrades containers without persistent storage would also solve the issue.

**Comment by mhoppal** [comment]
Can we include hooks like that in helm?

**Comment by timothyb89** [comment]
Should be fixed now that our init jobs are all idempotent (and we have the cleanup job so Helm cooperates)
